server:
  port: 9572

spring:
  application:
    name: server-gateway
  redis:
    host: 192.168.206.130
    port: 6380
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.206.130:8848
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: user_routh    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://server-user #匹配后提供服务的路由地址
          predicates:
            - Path=/user/**,/shippings/**         # 断言，路径相匹配的进行路由

        - id: product_routh   #路由的ID
          uri: lb://server-product #匹配后提供服务的路由地址
          predicates:
            - Path=/categories/**,/products/**         # 断言，路径相匹配的进行路由

        - id: cart_routh   #路由的ID
          uri: lb://server-cart #匹配后提供服务的路由地址
          predicates:
            - Path=/carts/**         # 断言，路径相匹配的进行路由

        - id: order_routh   #路由的ID
          uri: lb://server-order #匹配后提供服务的路由地址
          predicates:
            - Path=/orders/**         # 断言，路径相匹配的进行路由

        - id: payment_routh   #路由的ID
          uri: lb://server-payment #匹配后提供服务的路由地址
          predicates:
            - Path=/pay/**         # 断言，路径相匹配的进行路由

