server:
  port: 8200

spring:
  application:
    name: server-cart
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.206.130:3306/mall?characterEncoding=utf-8&useSSL=false
    username: root
    password: 159753
  redis:
    host: 192.168.206.130
    port: 6380
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.206.130:8848
    sentinel:
      transport:
        # 配置 sentinel dashboard地址
        dashboard: 192.168.206.130:8858
        # 指定和控制通信的端口，默认值8719，如不设置，会自动从8719开始扫描，依次+1，直到找到未被占用的端口
        port: 8719
    circuitbreaker:
      sentinel:
        enabled: true

feign:
  sentinel:
    enabled: true
